### ISSUE TITLE
Add lightmap baking

### ISSUE THREAD

**Issue by nasOS-official** [blackears/cyclopsLevelBuilder#111] opened 2023-12-13 14:43 UTC
Related to https://github.com/blackears/cyclopsLevelBuilder/issues/15.

Please add support for baking lightmaps or add a "Convert to mesh" button.

**Comment by Calinou** [comment] 2024-03-26 00:31
This issue is a duplicate of https://github.com/blackears/cyclopsLevelBuilder/issues/15.

Note that exporting to the Godot mesh format has been implemented as of [1.0.2](https://github.com/blackears/cyclopsLevelBuilder/releases/tag/v1.0.2), so you can do that then bake lightmaps afterwards. This is a destructive operation, so you'll want to keep a copy of your source CyclopsBlocks around.

**Closed** 2024-03-27 14:36 UTC
